spring:
  profiles:
    active: local
  session:
    store-type: redis
    timeout: 2592000
  #redis
  data:
    redis:
      host: 192.168.150.101
      port: 6379
      password: dopamine
      database: 0
      ttl: 3600
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lu-ai-code
    username: root
    password: admin
  application:
    name: lu-ai-code
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: admin
    password: 123456
    virtual-host: /

screenshot:
  pool:
    max-size: 4
    min-idle: 1

server:
  port: 8223
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lu.luaicode.controller
# knife4j
knife4j:
  enable: false
  setting:
    language: zh_cn

